registries:
  npm_registry:
    token: "${{secrets.NPM__REGISTRY__ACCESS_TOKEN}}"
    type: "npm-registry"
    url: "https://registry.npmjs.org"
updates:
  - commit-message:
      prefix: "chore: "
    directory: "/"
    package-ecosystem: "devcontainers"
    pull-request-branch-name:
      separator: "-"
    schedule:
      day: "saturday"
      interval: "weekly"
  - commit-message:
      prefix: "chore: "
    directory: "/"
    package-ecosystem: "github-actions"
    pull-request-branch-name:
      separator: "-"
    schedule:
      day: "tuesday"
      interval: "weekly"
  - commit-message:
      prefix: "chore: "
    directory: "/"
    package-ecosystem: "npm"
    pull-request-branch-name:
      separator: "-"
    registries:
      - "npm_registry"
    schedule:
      day: "monday"
      interval: "weekly"
version: 2
